apiVersion: v1
kind: Service
metadata:
  name: doctor-app-service
spec:
  type: NodePort
  selector:
    app: doctor-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30000
